version: "3"

# Note: License activation files (.ulf) are expected to be as follows:
# ../licenses/<version>/Unity_lic.ulf

# Let a CI system export these files during the build step from a safe credential store, e.g. Jenkins Credentials Plugin

services:
  unity5:
    image: gableroux/unity3d:5.6.3f1
    environment:
      - LICENSE_EMAIL=$EMAIL
      - LICENSE_PASSWORD=$PASSWORD
    volumes:
      - .:/root/project
      - ../licenses/5-6-3f1:/root/.local/share/unity3d/Unity
    command: bash -c "cp -R /root/project /root/project-local && mkdir -p /root/.cache/unity3d && /root/project-local/src/bash/unity-export-package.sh 5-6-3f1"

  unity2017:
    image: gableroux/unity3d:2017.4.9f1
    environment:
      - LICENSE_EMAIL=$EMAIL
      - LICENSE_PASSWORD=$PASSWORD
    volumes:
      - .:/root/project
      - ../licenses/2017-4-9f1:/root/.local/share/unity3d/Unity
    command: bash -c "cp -R /root/project /root/project-local && /root/project-local/src/bash/unity-export-package.sh 2017-4-9f1"
    
  unity2018:
    image: gableroux/unity3d:2018.4.9f1
    environment:
      - LICENSE_EMAIL=$EMAIL
      - LICENSE_PASSWORD=$PASSWORD
    volumes:
      - .:/root/project
      - ../licenses/2018-4-9f1:/root/.local/share/unity3d/Unity
    command: bash -c "cp -R /root/project /root/project-local && /root/project-local/src/bash/unity-export-package.sh 2018-4-9f1"

  unity2019:
    image: gableroux/unity3d:2019.2.11f1
    environment:
      - LICENSE_EMAIL=$EMAIL
      - LICENSE_PASSWORD=$PASSWORD
    volumes:
      - .:/root/project
      - ../licenses/2019-2-11f1:/root/.local/share/unity3d/Unity
    command: bash -c "cp -R /root/project /root/project-local && /root/project-local/src/bash/unity-export-package.sh 2019-2-11f1"
