version: "3"

# Note: License activation files (.ulf) are expected to be as follows:
# ../licenses/<version>/Unity_lic.ulf

# Let a CI system export these files during the build step from a safe credential store, e.g. Jenkins Credentials Plugin

services:
  unity2018:
    image: unityci/editor:ubuntu-2018.4.36f1-base-1
    environment:
      - LICENSE_EMAIL=$EMAIL
      - LICENSE_PASSWORD=$PASSWORD
    volumes:
      - .:/root/project
      - ../licenses/2018-4-36f1:/root/.local/share/unity3d/Unity
    command: bash -c "cp -R /root/project /root/project-local && /root/project-local/src/bash/unity-export-package.sh 2018-4-36f1"

  unity2019:
    image: unityci/editor:ubuntu-2019.4.40f1-base-1
    environment:
      - LICENSE_EMAIL=$EMAIL
      - LICENSE_PASSWORD=$PASSWORD
    volumes:
      - .:/root/project
      - ../licenses/2019-4-40f1:/root/.local/share/unity3d/Unity
    command: bash -c "cp -R /root/project /root/project-local && /root/project-local/src/bash/unity-export-package.sh 2019-4-40f1"

  unity2020:
    image: unityci/editor:ubuntu-2020.3.35f1-base-1
    environment:
      - LICENSE_EMAIL=$EMAIL
      - LICENSE_PASSWORD=$PASSWORD
    volumes:
      - .:/root/project
      - ../licenses/2020-3-35f1:/root/.local/share/unity3d/Unity
    command: bash -c "cp -R /root/project /root/project-local && /root/project-local/src/bash/unity-export-package.sh 2020-3-35f1"
